workflows:
  unsigned-swift-build:
    name: Unsigned Swift Build
    environment:
      xcode: 15.4                # 按需要改版本
      cocoapods: default         # 如项目用 CocoaPods
    scripts:
      - name: Pod install (如有)
        script: |
          [ -f Podfile ] && pod install --repo-update
      - name: Build .app (Release, 无签名)
        script: |
          xcodebuild \
            -workspace Tools.xcworkspace \
            -scheme Tools \
            -configuration Release \
            -derivedDataPath build/DerivedData \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            -sdk iphoneos \
            -arch arm64 \
            CONFIGURATION_BUILD_DIR=build/ios/iphoneos
    artifacts:
      - build/ios/iphoneos/*.app.zip